//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseServiceHost.ServiceReferenceDF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryPackage", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class QueryPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.MethodMetaData[] MethodCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReturnOneOnlyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.MethodMetaData[] MethodCollection {
            get {
                return this.MethodCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodCollectionField, value) != true)) {
                    this.MethodCollectionField = value;
                    this.RaisePropertyChanged("MethodCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryID {
            get {
                return this.QueryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryIDField, value) != true)) {
                    this.QueryIDField = value;
                    this.RaisePropertyChanged("QueryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryString {
            get {
                return this.QueryStringField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryStringField, value) != true)) {
                    this.QueryStringField = value;
                    this.RaisePropertyChanged("QueryString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnOneOnly {
            get {
                return this.ReturnOneOnlyField;
            }
            set {
                if ((this.ReturnOneOnlyField.Equals(value) != true)) {
                    this.ReturnOneOnlyField = value;
                    this.RaisePropertyChanged("ReturnOneOnly");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodMetaData", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class MethodMetaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EconomicFundamentalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.ParameterData[] ParameterDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RealTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.MethodMetaData[] SubMethodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TimeFrameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EconomicFundamentals {
            get {
                return this.EconomicFundamentalsField;
            }
            set {
                if ((this.EconomicFundamentalsField.Equals(value) != true)) {
                    this.EconomicFundamentalsField = value;
                    this.RaisePropertyChanged("EconomicFundamentals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodID {
            get {
                return this.MethodIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodIDField, value) != true)) {
                    this.MethodIDField = value;
                    this.RaisePropertyChanged("MethodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.ParameterData[] ParameterData {
            get {
                return this.ParameterDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterDataField, value) != true)) {
                    this.ParameterDataField = value;
                    this.RaisePropertyChanged("ParameterData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RealTime {
            get {
                return this.RealTimeField;
            }
            set {
                if ((this.RealTimeField.Equals(value) != true)) {
                    this.RealTimeField = value;
                    this.RaisePropertyChanged("RealTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.MethodMetaData[] SubMethods {
            get {
                return this.SubMethodsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubMethodsField, value) != true)) {
                    this.SubMethodsField = value;
                    this.RaisePropertyChanged("SubMethods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TimeFrame {
            get {
                return this.TimeFrameField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeFrameField, value) != true)) {
                    this.TimeFrameField = value;
                    this.RaisePropertyChanged("TimeFrame");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterData", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class ParameterData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AltFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FriendlyGroupNameListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FriendlySubEventListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FriendlyTimePeriodListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AltFlag {
            get {
                return this.AltFlagField;
            }
            set {
                if ((this.AltFlagField.Equals(value) != true)) {
                    this.AltFlagField = value;
                    this.RaisePropertyChanged("AltFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstTag {
            get {
                return this.FirstTagField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstTagField, value) != true)) {
                    this.FirstTagField = value;
                    this.RaisePropertyChanged("FirstTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FriendlyGroupNameList {
            get {
                return this.FriendlyGroupNameListField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendlyGroupNameListField, value) != true)) {
                    this.FriendlyGroupNameListField = value;
                    this.RaisePropertyChanged("FriendlyGroupNameList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FriendlySubEventList {
            get {
                return this.FriendlySubEventListField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendlySubEventListField, value) != true)) {
                    this.FriendlySubEventListField = value;
                    this.RaisePropertyChanged("FriendlySubEventList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FriendlyTimePeriodList {
            get {
                return this.FriendlyTimePeriodListField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendlyTimePeriodListField, value) != true)) {
                    this.FriendlyTimePeriodListField = value;
                    this.RaisePropertyChanged("FriendlyTimePeriodList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameter {
            get {
                return this.ParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterField, value) != true)) {
                    this.ParameterField = value;
                    this.RaisePropertyChanged("Parameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterType {
            get {
                return this.ParameterTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterTypeField, value) != true)) {
                    this.ParameterTypeField = value;
                    this.RaisePropertyChanged("ParameterType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerTransferPackage", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class AnswerTransferPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.PresentationPackage[] PresentationTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.ComputedResultTable ProcessedResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.RawDataResultTable[] RawDataResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] ResultSymbolsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserQuerySessionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.PresentationPackage[] PresentationTypes {
            get {
                return this.PresentationTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentationTypesField, value) != true)) {
                    this.PresentationTypesField = value;
                    this.RaisePropertyChanged("PresentationTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.ComputedResultTable ProcessedResults {
            get {
                return this.ProcessedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessedResultsField, value) != true)) {
                    this.ProcessedResultsField = value;
                    this.RaisePropertyChanged("ProcessedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Query {
            get {
                return this.QueryField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryField, value) != true)) {
                    this.QueryField = value;
                    this.RaisePropertyChanged("Query");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryID {
            get {
                return this.QueryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryIDField, value) != true)) {
                    this.QueryIDField = value;
                    this.RaisePropertyChanged("QueryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.RawDataResultTable[] RawDataResults {
            get {
                return this.RawDataResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RawDataResultsField, value) != true)) {
                    this.RawDataResultsField = value;
                    this.RaisePropertyChanged("RawDataResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] ResultSymbols {
            get {
                return this.ResultSymbolsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultSymbolsField, value) != true)) {
                    this.ResultSymbolsField = value;
                    this.RaisePropertyChanged("ResultSymbols");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserQuerySessionID {
            get {
                return this.UserQuerySessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserQuerySessionIDField, value) != true)) {
                    this.UserQuerySessionIDField = value;
                    this.RaisePropertyChanged("UserQuerySessionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComputedResultTable", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class ComputedResultTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] ComputedResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string>[] DetailedFactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenericField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HeaderDataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] KeyFieldIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] ComputedResults {
            get {
                return this.ComputedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputedResultsField, value) != true)) {
                    this.ComputedResultsField = value;
                    this.RaisePropertyChanged("ComputedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string>[] DetailedFacts {
            get {
                return this.DetailedFactsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailedFactsField, value) != true)) {
                    this.DetailedFactsField = value;
                    this.RaisePropertyChanged("DetailedFacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Generic {
            get {
                return this.GenericField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericField, value) != true)) {
                    this.GenericField = value;
                    this.RaisePropertyChanged("Generic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] HeaderDataType {
            get {
                return this.HeaderDataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderDataTypeField, value) != true)) {
                    this.HeaderDataTypeField = value;
                    this.RaisePropertyChanged("HeaderDataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Headers {
            get {
                return this.HeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadersField, value) != true)) {
                    this.HeadersField = value;
                    this.RaisePropertyChanged("Headers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] KeyFieldIndex {
            get {
                return this.KeyFieldIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyFieldIndexField, value) != true)) {
                    this.KeyFieldIndexField = value;
                    this.RaisePropertyChanged("KeyFieldIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PresentationPackage", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class PresentationPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainWidgetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainWidgetAltNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SubWidgetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SubWidgetsAltNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainWidget {
            get {
                return this.MainWidgetField;
            }
            set {
                if ((object.ReferenceEquals(this.MainWidgetField, value) != true)) {
                    this.MainWidgetField = value;
                    this.RaisePropertyChanged("MainWidget");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainWidgetAltName {
            get {
                return this.MainWidgetAltNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MainWidgetAltNameField, value) != true)) {
                    this.MainWidgetAltNameField = value;
                    this.RaisePropertyChanged("MainWidgetAltName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SubWidgets {
            get {
                return this.SubWidgetsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubWidgetsField, value) != true)) {
                    this.SubWidgetsField = value;
                    this.RaisePropertyChanged("SubWidgets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SubWidgetsAltName {
            get {
                return this.SubWidgetsAltNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubWidgetsAltNameField, value) != true)) {
                    this.SubWidgetsAltNameField = value;
                    this.RaisePropertyChanged("SubWidgetsAltName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RawDataResultTable", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class RawDataResultTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.ChartDataPairing[] ChartReadyDataResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][][] DataResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTimeFrameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] HeaderDataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] HeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.HighlightRegion[] HighLightRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseServiceHost.ServiceReferenceDF.PerformanceStats[] PerformanceStatisticsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SummariesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.ChartDataPairing[] ChartReadyDataResults {
            get {
                return this.ChartReadyDataResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartReadyDataResultsField, value) != true)) {
                    this.ChartReadyDataResultsField = value;
                    this.RaisePropertyChanged("ChartReadyDataResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][][] DataResults {
            get {
                return this.DataResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataResultsField, value) != true)) {
                    this.DataResultsField = value;
                    this.RaisePropertyChanged("DataResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTimeFrame {
            get {
                return this.DataTimeFrameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTimeFrameField, value) != true)) {
                    this.DataTimeFrameField = value;
                    this.RaisePropertyChanged("DataTimeFrame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] HeaderDataType {
            get {
                return this.HeaderDataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderDataTypeField, value) != true)) {
                    this.HeaderDataTypeField = value;
                    this.RaisePropertyChanged("HeaderDataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] Headers {
            get {
                return this.HeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadersField, value) != true)) {
                    this.HeadersField = value;
                    this.RaisePropertyChanged("Headers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.HighlightRegion[] HighLightRegion {
            get {
                return this.HighLightRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.HighLightRegionField, value) != true)) {
                    this.HighLightRegionField = value;
                    this.RaisePropertyChanged("HighLightRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseServiceHost.ServiceReferenceDF.PerformanceStats[] PerformanceStatistics {
            get {
                return this.PerformanceStatisticsField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceStatisticsField, value) != true)) {
                    this.PerformanceStatisticsField = value;
                    this.RaisePropertyChanged("PerformanceStatistics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Summaries {
            get {
                return this.SummariesField;
            }
            set {
                if ((object.ReferenceEquals(this.SummariesField, value) != true)) {
                    this.SummariesField = value;
                    this.RaisePropertyChanged("Summaries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChartDataPairing", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class ChartDataPairing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ColumnHeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] GenericStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RowHeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XaxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YaxisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ColumnHeaders {
            get {
                return this.ColumnHeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnHeadersField, value) != true)) {
                    this.ColumnHeadersField = value;
                    this.RaisePropertyChanged("ColumnHeaders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] GenericStr {
            get {
                return this.GenericStrField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericStrField, value) != true)) {
                    this.GenericStrField = value;
                    this.RaisePropertyChanged("GenericStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RowHeaders {
            get {
                return this.RowHeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.RowHeadersField, value) != true)) {
                    this.RowHeadersField = value;
                    this.RaisePropertyChanged("RowHeaders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xaxis {
            get {
                return this.XaxisField;
            }
            set {
                if ((object.ReferenceEquals(this.XaxisField, value) != true)) {
                    this.XaxisField = value;
                    this.RaisePropertyChanged("Xaxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Yaxis {
            get {
                return this.YaxisField;
            }
            set {
                if ((object.ReferenceEquals(this.YaxisField, value) != true)) {
                    this.YaxisField = value;
                    this.RaisePropertyChanged("Yaxis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HighlightRegion", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class HighlightRegion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AxisIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeriesIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AxisIndex {
            get {
                return this.AxisIndexField;
            }
            set {
                if ((this.AxisIndexField.Equals(value) != true)) {
                    this.AxisIndexField = value;
                    this.RaisePropertyChanged("AxisIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EndDateTime {
            get {
                return this.EndDateTimeField;
            }
            set {
                if ((this.EndDateTimeField.Equals(value) != true)) {
                    this.EndDateTimeField = value;
                    this.RaisePropertyChanged("EndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeriesIndex {
            get {
                return this.SeriesIndexField;
            }
            set {
                if ((this.SeriesIndexField.Equals(value) != true)) {
                    this.SeriesIndexField = value;
                    this.RaisePropertyChanged("SeriesIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((this.StartDateTimeField.Equals(value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceStats", Namespace="http://schemas.datacontract.org/2004/07/AnswerEngineOneService")]
    [System.SerializableAttribute()]
    public partial class PerformanceStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerformanceStatsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] StatsLogField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Headers {
            get {
                return this.HeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadersField, value) != true)) {
                    this.HeadersField = value;
                    this.RaisePropertyChanged("Headers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PerformanceStatsType {
            get {
                return this.PerformanceStatsTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceStatsTypeField, value) != true)) {
                    this.PerformanceStatsTypeField = value;
                    this.RaisePropertyChanged("PerformanceStatsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] StatsLog {
            get {
                return this.StatsLogField;
            }
            set {
                if ((object.ReferenceEquals(this.StatsLogField, value) != true)) {
                    this.StatsLogField = value;
                    this.RaisePropertyChanged("StatsLog");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDF.IAnswerEngineOneService")]
    public interface IAnswerEngineOneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnswerEngineOneService/ProcessQuery", ReplyAction="http://tempuri.org/IAnswerEngineOneService/ProcessQueryResponse")]
        DatabaseServiceHost.ServiceReferenceDF.AnswerTransferPackage ProcessQuery(DatabaseServiceHost.ServiceReferenceDF.QueryPackage queryPackage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnswerEngineOneService/GetAllCompletedPatternDefaults", ReplyAction="http://tempuri.org/IAnswerEngineOneService/GetAllCompletedPatternDefaultsResponse" +
            "")]
        DatabaseServiceHost.ServiceReferenceDF.AnswerTransferPackage GetAllCompletedPatternDefaults(string exchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnswerEngineOneService/GetAllEmergingPatternDefaults", ReplyAction="http://tempuri.org/IAnswerEngineOneService/GetAllEmergingPatternDefaultsResponse")]
        DatabaseServiceHost.ServiceReferenceDF.AnswerTransferPackage GetAllEmergingPatternDefaults(string exchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnswerEngineOneService/GetDataResult", ReplyAction="http://tempuri.org/IAnswerEngineOneService/GetDataResultResponse")]
        DatabaseServiceHost.ServiceReferenceDF.AnswerTransferPackage GetDataResult(string queryId, string selectingSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnswerEngineOneService/GetSymbolData", ReplyAction="http://tempuri.org/IAnswerEngineOneService/GetSymbolDataResponse")]
        double[][] GetSymbolData(string symbolID, string timeFrame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnswerEngineOneService/GetData", ReplyAction="http://tempuri.org/IAnswerEngineOneService/GetDataResponse")]
        DatabaseServiceHost.ServiceReferenceDF.QueryPackage GetData(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnswerEngineOneServiceChannel : DatabaseServiceHost.ServiceReferenceDF.IAnswerEngineOneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnswerEngineOneServiceClient : System.ServiceModel.ClientBase<DatabaseServiceHost.ServiceReferenceDF.IAnswerEngineOneService>, DatabaseServiceHost.ServiceReferenceDF.IAnswerEngineOneService {
        
        public AnswerEngineOneServiceClient() {
        }
        
        public AnswerEngineOneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnswerEngineOneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnswerEngineOneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnswerEngineOneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DatabaseServiceHost.ServiceReferenceDF.AnswerTransferPackage ProcessQuery(DatabaseServiceHost.ServiceReferenceDF.QueryPackage queryPackage) {
            return base.Channel.ProcessQuery(queryPackage);
        }
        
        public DatabaseServiceHost.ServiceReferenceDF.AnswerTransferPackage GetAllCompletedPatternDefaults(string exchange) {
            return base.Channel.GetAllCompletedPatternDefaults(exchange);
        }
        
        public DatabaseServiceHost.ServiceReferenceDF.AnswerTransferPackage GetAllEmergingPatternDefaults(string exchange) {
            return base.Channel.GetAllEmergingPatternDefaults(exchange);
        }
        
        public DatabaseServiceHost.ServiceReferenceDF.AnswerTransferPackage GetDataResult(string queryId, string selectingSymbol) {
            return base.Channel.GetDataResult(queryId, selectingSymbol);
        }
        
        public double[][] GetSymbolData(string symbolID, string timeFrame) {
            return base.Channel.GetSymbolData(symbolID, timeFrame);
        }
        
        public DatabaseServiceHost.ServiceReferenceDF.QueryPackage GetData(int value) {
            return base.Channel.GetData(value);
        }
    }
}
